### PR TITLE
Bugfix for uninterrupted receive loop

### LINKED ISSUE #5: plugin throws errors if not receiving messages and crashes on exit
On logstash 1.5.0 on macosx:

```
input {
  zeromq {
    topology => "pushpull"
      address => ["tcp://127.0.0.1:2100"]
      mode => "client"
      sockopt => ["ZMQ::RCVTIMEO", 5000]
  }
}
output { stdout { codec => rubydebug } }
```

```
Logstash startup completed
ZeroMQ error while in recv_string {:error_code=>-1, :level=>:error}
ZeroMQ error while in recv_string {:error_code=>-1, :level=>:error}
ZeroMQ error while in recv_string {:error_code=>-1, :level=>:error}
ZeroMQ error while in recv_string {:error_code=>-1, :level=>:error}
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Assertion failed: ok (mailbox.cpp:82)
[1]    5760 abort (core dumped)  bin/logstash -f zmq-client.conf
```

migrated from https://github.com/elastic/logstash/issues/1320

### LINKED ISSUE #17: Uninterrupted receive loop (CPU 100%)
ZeroMQ input uses 100% CPU

Even without actual traffic, the zeromq input plugin produces 100% load. The reason is the ZMQ::DONTWAIT setting in https://github.com/logstash-plugins/logstash-input-zeromq/blob/master/lib/logstash/inputs/zeromq.rb#L132, introduced by https://github.com/logstash-plugins/logstash-input-zeromq/commit/cef68df3d53e9bcd335d377e317fc8f6acfcb350

The ZMQ::DONTWAIT setting (http://api.zeromq.org/3-0:zmq-recv) enables the non-blocking mode on the ZeroMQ socket. If no message is available, on the socket, the recv_string method returns ZMQ::EAGAINT and the next on line 133 is executed. This leads to an endless loop of lines 128 to 133 and therefore to 100% CPU usage (at least on one CPU core).

Steps to reproduce:

Start logstash with the following config and watch the CPU, for example with top

```
input {
  zeromq {
    topology => "pushpull"
  }
}
output {
  stdout {}
}
```

I suggest to change the implementation to use ZMQ::RCVTIMEO (for example with a value of 1000) instead of ZMQ::DONTWAIT.

### PR DESCRIPTION
**Pull request by breml**
Replace the uninterrupted receive loop (non-blocking) with
a blocking loop with a default timeout of 1000ms.

Restores compatibility with zeromq output plugin for util/zeromq.rb as well, if logstash-plugins/logstash-output-zeromq#13 is merged.

Closes #17 
May also be related to #5

### CODE REVIEW

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

File: lib/logstash/util/zeromq.rb [hunk 1]
```diff
@@ -20,8 +20,8 @@ def setup(socket, address)
     @logger.info("0mq: #{server? ? 'connected' : 'bound'}", :address => address)
   end
 
-  def error_check(rc, doing)
-    unless ZMQ::Util.resultcode_ok?(rc)
+  def error_check(rc, doing, eagain_not_error = false)
```
Comment (breml) [inline lib/logstash/util/zeromq.rb:23]: Because function signature of error_check is changed and util/zeromq.rb is present in zeromq input and output plugin, this PR has a dependecy to logstash-plugins/logstash-output-zeromq/pull/13.

**Comment by breml** [comment]
Could please someone give me some feedback?

**Comment by erikthorselius** [comment]
This would be really good if any maintainer could have a look on this.

**Comment by nukemberg** [comment]
OK, had a look. The patch looks straight forward. I do need to run some tests so it will take a few days to close this. Thanks!

**Comment by erikthorselius** [comment]
I'm really interested in this fix. I'm having two zeromq inputs taking up half of the server cpu capacity. So if there is any thing I can do to help, feel free to delegate.

**Comment by breml** [comment]
@erikthorselius Have you tried this PR in your setup? Did it solve your problem?

**Comment by erikthorselius** [comment]
Looks good! I'm new to logstash but here is how I tested. My server is running coreos so I built a docker container.

My dockerfile:

```
FROM logstash
COPY logstash-input-zeromq-2.0.2.gem /tmp/
RUN /opt/logstash/bin/plugin uninstall logstash-input-zeromq
RUN /opt/logstash/bin/plugin install /tmp/logstash-input-zeromq-2.0.2.gem
CMD ["logstash", "agent"]
```

```
gem build logstash-input-zeromq.gemspec
docker build -t logstash-with-zeromq-patch .
docker save -o logstash-with-zeromq-patch logstash-with-zeromq-patch
scp logstash-with-zeromq-patch server:
```

and on my server

```
docker load -i logstash-with-zeromq-patch
docker run --rm --name logstash -p 2120:2120 -v /home/logstash/conf:/data logstash-with-zeromq-patch logstash -f /data/logstash.conf
```

Same process is now down to 1.8% instead of 200%

```
input {
  zeromq {
    topology => "pushpull"
    tags => ["pushpull"]
  }
  zeromq {
    mode => "client"
    address => ["tcp://192.168.1.3:7555"]
    topology => "pubsub"
    topic => "sensor"
    tags => ["pubsub"]
  }
}
filter {
  date {
    match => ["unix_timestamp", "UNIX"]
  }
}
output {
  elasticsearch {
    hosts => ["192.168.1.3:9200"]
  }
}
```

File: lib/logstash/inputs/zeromq.rb [hunk 2]
```diff
@@ -69,7 +69,10 @@ class LogStash::Inputs::ZeroMQ < LogStash::Inputs::Base
   #  * `ZMQ::SWAP_SIZE` - space for disk overflow
   #
   # example: `sockopt => ["ZMQ::HWM", 50, "ZMQ::IDENTITY", "my_named_queue"]`
-  config :sockopt, :validate => :hash
+  #
+  # defaults to: `sockopt => ["ZMQ::RCVTIMEO", "1000"]`, which has the effect of "interrupting"
+  # the recv operation at least once every second to allow for properly shutdown handling.
+  config :sockopt, :validate => :hash, :default => [ "ZMQ::RCVTIMEO", "1000" ]
```
Comment (jordansissel) [inline lib/logstash/inputs/zeromq.rb]: This should probably be `:default => { "ZMQ::RCVTIMEO" => "1000" }` right?

**Comment by jordansissel** [comment]
Given @erikthorselius's success report, I'm OK merging this. Code LGTM except for my one comment about the hash default value (should use hash syntax, not array).

@breml Can you address my comment? I'm happy to merge once done. :)

**Comment by erikthorselius** [comment]
It fixed my cpu problem but it seems that I don't receive any messages. 
screenshot 2016-01-07 08 34 39
I'm at work right now but I can try to debug when I'm home.

File: lib/logstash/inputs/zeromq.rb (hunk 2 above)
Comment (breml) [inline lib/logstash/inputs/zeromq.rb]: I agree, it should be a hash. I just followed the existing example, which provides an array with an even count of elements, which gets converted to a hash in https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L381 (lines 381 - 398). I update the PR, including the existing comment/example.

**Comment by breml** [comment]
@erikthorselius Please see my comment regarding `lib/logstash/util/zeromq.rb`. This file was shared in Logstash prior to version 1.5. Now both plugins, logstash-input-zeromq and logstash-output-zeromq do provide this file. Therefore it is important to update this file in both plugins at the same time because otherwise it could happen that the logstash-input-zeromq plugin is using the wrong version of this file. (see my reference to logstash-plugins/logstash-output-zeromq#13 above)

@jordansissel this is quiet an annoying issue. I suggest to either really duplicate the code by moving `lib/logstash/util/zeromq.rb` to `lib/logstash/input`respectively `lib/logstash/output` or by putting `lib/logstash/util/zeromq.rb` into a separate gem file, which is really shared and therefore present only once.

**Comment by erikthorselius** [comment]
Maybe a stupid question but how do I update that? Would it work to uninstall logstash-output-zeromq?

**Comment by breml** [comment]
@erikthorselius Uninstalling the logstash-output-zeromq plugin may work. If it doesn't, I recommend to rename `./vendor/bundle/jruby/1.9/gems/logstash-output-zeromq-2.0.2/lib/logstash/util/zeromq.rb` for example to `zeromq.rb.bak`. This will prevent ruby from loading this file which will result in ruby loading the correct one from the logstash-input-zeromq plugin.

**Comment by erikthorselius** [comment]
I'm so sorry forgetting this. I blame work.

I have tested this again and it works perfect! The cpu goes from 200% to 0.3 % and i still receive logs.

**Comment by nukemberg** [comment]
i'm going to start working on refactoring common zeromq code to a new gem, this should ease maintenance of logstash zeromq plugins. i'll update soon.

**Comment by suyograo** [comment]
@breml Thanks for this. Could you please bump the version in the gemspec and add a changelog? I can merge this, then and publish a new version

**Comment by breml** [comment]
@suyograo Sure I would like to update gemspec and changelog, but this change should not be merged without either https://github.com/logstash-plugins/logstash-output-zeromq/pull/13 or the refactoring mentioned by @avishai-ish-shalom, because of https://github.com/logstash-plugins/logstash-input-zeromq/pull/18/files#r47354652.

**Comment by nukemberg** [comment]
This PR is on hold until logstash-mixin-zeromq is integrated. cc @breml
